apiVersion: v1
kind: Service
metadata:
  name: jaeger-nodeport
  namespace: coding
spec:
  ports:
    - name: http-query
      port: 16686
      protocol: TCP
      targetPort: 16686
      nodePort: 16686
    - name: grpc-query
      port: 16685
      protocol: TCP
      targetPort: 16685
      nodePort: 16686
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: NodePort
  externalIPs:
    - 9.135.147.70